### ISSUE TITLE
Error when pip installing PyTrip98 on Windows 10 computer.

### ISSUE THREAD

**Issue by Tibazz** [pytrip/pytrip#323]
Niels told me to include this error-message when installing PyTrip98 via pip on my Windows 10 laptop.

   ......
   copying pytrip\data\OER_furusawa_HSG_C12.dat -> build\lib.win32-3.6\pytrip\data
   copying pytrip\data\OER_furusawa_V79_C12.dat -> build\lib.win32-3.6\pytrip\data 
   UPDATING build\lib.win32-3.6\pytrip/_version.py
   set build\lib.win32-3.6\pytrip/_version.py to '1.4.1
   running build_ext
   building 'pytriplib' extension
   
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

Do i need to install Microsoft Visual C++ 14.0 to get PyTrip98 to work ?
Thank you.

**Comment by grzanka** [comment]
First of all how did you install python ? From https://www.python.org/downloads/ (standard one) or from https://www.continuum.io/downloads (Anaconda) ?

Can you also type:
```
pip -V
python -V
```
and paste here the result (might be a screenshot).

I wanted to check which versions of pip and python you have installed.

**Comment by Tibazz** [comment]
Installed via homepage, then i installed Anaconda for a while but it did not help in me trying to install PyTrip98 so i uninstalled it and as of now i only have Python 3.6 and no Anaconda.
```
C:\Users\Tibazz\Google Drive\Universitetet\Master Project\WORK>pip -V 
pip 9.0.1 from c:\users\tibazz\appdata\local\programs\python\python36-32\lib\site-packages (python 3.6)
```

```
C:\Users\Tibazz\Google Drive\Universitetet\Master Project\WORK>python -V
Python 3.6.0
```

**Comment by grzanka** [comment]
OK, can you try with anaconda and do following things:
1. Uninstall local python
2. install Anaconda
3. do "conda install scipy"
4. do pip install pytrip98

The problem is related to compilation of scipy.

The other method is to use standard python and scipy from gohlke page: http://www.lfd.uci.edu/~gohlke/pythonlibs/

Please let me know if it helps.

**Comment by Tibazz** [comment]
As of right now i acctually have scipy installed from the gohlke page and its working, when i had anaconda installed i could install scipy but not get it running for some unknown reason.

I could try and uninstall python and go with anaconda but as of right now i dont want to go through that headache again, maby at the end of this week : )

Can i ask thou, is there a wheel file i can download for PyTrip98 ? because that seems to be the most consistent way for me to install modules.

**Comment by grzanka** [comment]
Well, the wheel files are here: https://pypi.python.org/pypi/pytrip98

pytrip98 has a C extension and most of the wheel files have precompiled version of it (shared library .so for Linux and .pyd file for Windows).

I'd say its more convenient to install it is simply to type "pip install pytrip98" as with every other package.

Can you check if after installation of scipy (from gohlke) and after typing "pip install pytrip98" you still have problems ?

Did you also installed numpy from gohlke repo ?

**Comment by Tibazz** [comment]
![1](https://cloud.githubusercontent.com/assets/25507492/24240862/59c57cea-0fb3-11e7-9c98-153e4826d3af.PNG)

![1point5](https://cloud.githubusercontent.com/assets/25507492/24240869/5f17ed40-0fb3-11e7-906b-fc8b2c1ffc4f.PNG)

![2](https://cloud.githubusercontent.com/assets/25507492/24240871/61358dd0-0fb3-11e7-8485-6f679c2295ec.PNG)

![3](https://cloud.githubusercontent.com/assets/25507492/24240877/64484134-0fb3-11e7-9df4-6c7534c33baf.PNG)

**Comment by grzanka** [comment]
OK, now I see the issue - precompiled wheel is missing for python 3.6 , so in your case pip is fetching source package.

Thanks for pointing to that problem !

Right now we have Windows wheels for python 2.7 and 3.5
I will add it for python 3.6 also. Should be done this week, once another issue https://github.com/pytrip/pytrip/issues/327 is fixed.

**Comment by grzanka** [comment]
@Tibazz I've made pytrip 1.5.0 which should work on Windows with Python 3.6
Could you please try to install it via pip and check if it works ?

**Comment by Tibazz** [comment]
Sweet ! i could download and install the module :)
I am a bit confused thou, i dont seem to have the pytrip.ddd.DDD directory in there, am i using it right ?

```import pytrip as pt```
```whatever = pt.ddd.DDD()```
```AttributeError: module 'pytrip' has no attribute 'DDD'```

**Comment by Tibazz** [comment]
seem to have it on my computer thou : /

![1](https://cloud.githubusercontent.com/assets/25507492/24355407/17429042-12f6-11e7-997f-0209488ef410.PNG)

**Comment by grzanka** [comment]
Concerning ddd can you make separate issue? Did you downloaded wheel or
simply Installed it via pip?

27.03.2017 13:57 "Tibor Marusic" <notifications@github.com> napisał(a):

**Comment by Tibazz** [comment]
I installed via pip, seemed to be working fine.

**Comment by grzanka** [comment]
OK, so I am closing this issue as it is related to Windows installation problem. All the other stuff I will treat in separate issues.
